name: Deploy Board Game Agent to Hugging Face Spaces

on:
  push:
    branches:
      - main # Or your default deployment branch

jobs:
  deploy_to_hf_space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python setup here is mostly for the huggingface-cli, actual app runs in Docker.
      - name: Set up Python for CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install huggingface_hub for CLI
        run: pip install huggingface_hub

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }} # e.g., "YourUsername/YourSpaceName"
        run: |
          echo "Logging into Hugging Face Hub..."
          # Ensure huggingface_hub is installed for the CLI
          pip install huggingface_hub
          huggingface-cli login --token $HF_TOKEN --add-to-git-credential
          
          # echo "Ensuring Space repository exists for $HF_SPACE_ID..."
          # huggingface-cli repo create $HF_SPACE_ID --type space
          # Note: For Docker SDK, the --sdk and --python flags are not needed here.
          # The presence of a Dockerfile in your pushed code signals HF to use Docker.
          
          # Create a temporary directory for cloning the Space repo
          TEMP_SPACE_DIR=$(mktemp -d)
          echo "Cloning Space repo $HF_SPACE_ID into $TEMP_SPACE_DIR"
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE_ID "$TEMP_SPACE_DIR"
          
          echo "Syncing files to Space repository..."
          rsync -av --delete \
            --include="data/" \
            --include="data/supported_games.txt" \
            --exclude="data/*" \
            --exclude=".git/" \
            --exclude=".github/" \
            --exclude="tests/" \
            --exclude="*" \
            ./ "$TEMP_SPACE_DIR/"

          echo "Committing and pushing to Space..."
          cd "$TEMP_SPACE_DIR"
          git lfs track "*.safetensors" # Good practice if large model files are ever added
          git add .
          
          # Commit only if there are changes
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update Space from GitHub Action (workflow: ${GITHUB_WORKFLOW}, run: ${GITHUB_RUN_ID})"
            git push origin main # Assumes the Space repo's default branch is 'main'
          else
            echo "No changes to commit to Space repo."
          fi
          
          echo "Deployment script finished. Hugging Face will now build the Docker image based on Dockerfile."